/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranslateLanguageRouteImport } from './routes/translate.$language'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateLanguageRoute = TranslateLanguageRouteImport.update({
  id: '/translate/$language',
  path: '/translate/$language',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/translate/$language': typeof TranslateLanguageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/translate/$language': typeof TranslateLanguageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/translate/$language': typeof TranslateLanguageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/translate/$language'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/translate/$language'
  id: '__root__' | '/' | '/translate/$language'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TranslateLanguageRoute: typeof TranslateLanguageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/$language': {
      id: '/translate/$language'
      path: '/translate/$language'
      fullPath: '/translate/$language'
      preLoaderRoute: typeof TranslateLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TranslateLanguageRoute: TranslateLanguageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
